name: deploy

#on:
#  release:
#    types: [ created ]

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: ${{ secrets.OSSRH_PGP_PASSPHRASE }}
          gpg-private-key: ${{ secrets.OSSRH_PGP_PRIVATE_KEY }}

      - name: Deploy
        run: mvn -DskipTests=true deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_PGP_PASSPHRASE }}
